# Generated by Django 5.2 — OrderItem хранит конкретное предложение (ProductInfo).

import django.db.models.deletion
from django.db import migrations, models


def forwards_fill_product_info(apps, schema_editor):
    OrderItem = apps.get_model('backend', 'OrderItem')
    ProductInfo = apps.get_model('backend', 'ProductInfo')
    for item in OrderItem.objects.all():
        if not item.product_id or not item.shop_id:
            item.delete()
            continue
        pi = (
            ProductInfo.objects.filter(product_id=item.product_id, shop_id=item.shop_id)
            .order_by('id')
            .first()
        )
        if not pi:
            item.delete()
            continue
        item.product_info_id = pi.pk
        item.save(update_fields=['product_info_id'])


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_confirmemailtoken_user_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_product_shop',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_info',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='order_items',
                to='backend.productinfo',
                verbose_name='Предложение',
            ),
        ),
        migrations.RunPython(forwards_fill_product_info, backwards_noop),
        migrations.AlterField(
            model_name='orderitem',
            name='product_info',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='order_items',
                to='backend.productinfo',
                verbose_name='Предложение',
            ),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shop',
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product_info'), name='unique_order_product_info'),
        ),
    ]
